export const formPropertyRequiredFields = {
    'step_1' : [
      'division_id',
      'user_id',
      'type_id',
      'city_id',
      'area_id',
      'building_id',
      'is_for_rent',
      'is_for_sale',
      'street',
      'category_select'
    ],

    'step_2' : [
      'unit_number',
      'name',
      'status_id',
      'availability',
      'commercial_building_class',
      'commercial_developer',
      'commercial_building_name',
      'commercial_office_floor',
      'commercial_occupant_number',
      'commercial_office_type',
      'commercial_office_setup',
      'description',
    ],

    'step_3' : [
        'is_for_rent',
        'is_for_sale',
        'sale_price',
      'original_sale_price',
      'rent_price',
      'original_rent_price',
      'price_per',
      'price_rate',
      'discount_percentage',
      'floor_area',
      'advance',
      'advance_unit',
      'deposit',
      'deposit_unit',
      'lot_area',
      'bedrooms',
      'bathrooms',
      'car_space',
      'minimum_lease_term',
      'minimum_lease_term_unit',
      'association_dues',
      'escalation',
      'telcos',
      'commercial_aircon',
      'commercial_aircon_operation',
      'slideshare_id',
      'youtube_id',
      'optional_contents',
    ],

    'step_4' : ['condition_id', 'amenities', 'division_id'],

    'step_5' : [
      'remarks',
      'fixed_image_price',
      'price_per_image',
      'watermark_agreement',
    ]
}