<script setup lang="ts">
/**
 * Deal-scoped tasks panel.
 *
 * Shows tasks attached to a deal — both manually created and
 * auto-generated by the stage-transition trigger
 * (deals_apply_task_templates_fn). Each task surfaces its origin via
 * the auto-generated badge so operators see "this was auto-created
 * when the deal moved to documentation."
 *
 * Actions: complete, snooze, recommendations link.
 */
import { ref, computed, onMounted, watch } from 'vue'
import { showToast } from '~/helpers/helpers'

type Task = {
  id: string
  title: string
  description: string | null
  due_at: string | null
  completed_at: string | null
  auto_generated: boolean
  metadata: Record<string, any> | null
  created_at: string
}

const props = defineProps<{
  dealId: string
}>()

const supabase = useSupabaseClient()
const tasks = ref<Task[]>([])
const loading = ref(true)
const submitting = ref<Record<string, boolean>>({})
const showCompleted = ref(false)

async function load() {
  if (!props.dealId) return
  loading.value = true
  try {
    let req: any = (supabase as any)
      .from('tasks')
      .select('id, title, description, due_at, completed_at, auto_generated, metadata, created_at')
      .eq('deal_id', props.dealId)
      .order('completed_at', { ascending: true, nullsFirst: true })
      .order('due_at', { ascending: true, nullsFirst: false })
    if (!showCompleted.value) req = req.is('completed_at', null)
    const { data, error } = await req
    if (error) throw error
    tasks.value = (data || []) as Task[]
  } catch (err: any) {
    showToast({
      title: err?.message || 'Failed to load tasks',
      icon: 'error',
    })
  } finally {
    loading.value = false
  }
}

watch(() => [props.dealId, showCompleted.value], load)
onMounted(load)

async function complete(t: Task) {
  if (submitting.value[t.id]) return
  submitting.value[t.id] = true
  try {
    await $fetch(`/api/tasks/${t.id}/complete`, { method: 'POST' })
    showToast({ title: 'Task completed', icon: 'success' })
    await load()
  } catch (err: any) {
    showToast({
      title: err?.statusMessage || err?.message || 'Failed to complete',
      icon: 'error',
    })
  } finally {
    delete submitting.value[t.id]
  }
}

async function snooze(t: Task, days: number) {
  if (submitting.value[t.id]) return
  submitting.value[t.id] = true
  try {
    await $fetch(`/api/tasks/${t.id}/snooze`, {
      method: 'POST',
      body: { days },
    })
    showToast({ title: `Snoozed ${days} day${days === 1 ? '' : 's'}`, icon: 'success' })
    await load()
  } catch (err: any) {
    showToast({
      title: err?.statusMessage || err?.message || 'Failed to snooze',
      icon: 'error',
    })
  } finally {
    delete submitting.value[t.id]
  }
}

function dueLabel(t: Task): string {
  if (!t.due_at) return ''
  const due = new Date(t.due_at).getTime()
  if (!Number.isFinite(due)) return ''
  const diffMs = due - Date.now()
  if (diffMs < 0) return `overdue ${Math.round(-diffMs / 86_400_000)}d`
  if (diffMs < 3_600_000) return `in ${Math.round(diffMs / 60_000)}m`
  if (diffMs < 86_400_000) return `in ${Math.round(diffMs / 3_600_000)}h`
  return `in ${Math.round(diffMs / 86_400_000)}d`
}
function dueClass(t: Task): string {
  if (!t.due_at || t.completed_at) return 'text-muted-foreground'
  const due = new Date(t.due_at).getTime()
  if (Number.isFinite(due) && due < Date.now()) return 'text-destructive font-semibold'
  return 'text-foreground'
}

const visibleTasks = computed(() => tasks.value)
const isEmpty = computed(() => !loading.value && visibleTasks.value.length === 0)
</script>

<template>
  <section class="rounded-xl border border-border bg-background p-4">
    <header class="mb-3 flex items-baseline justify-between gap-3">
      <div>
        <h3 class="text-sm font-semibold text-foreground">Tasks</h3>
        <p class="text-xs text-muted-foreground">
          Auto-generated checklist + manual follow-ups for this deal.
        </p>
      </div>
      <label class="flex items-center gap-1.5 text-xs text-foreground">
        <input
          v-model="showCompleted"
          type="checkbox"
          class="h-3.5 w-3.5 cursor-pointer accent-blue-500"
        />
        Show completed
      </label>
    </header>

    <div
      v-if="loading"
      class="rounded-md border border-border bg-muted/50 p-4 text-xs text-muted-foreground"
    >
      Loading…
    </div>
    <div
      v-else-if="isEmpty"
      class="rounded-md border border-dashed border-border bg-muted/50 p-4 text-xs text-muted-foreground"
    >
      No tasks for this deal yet. Tasks auto-generate when the deal
      moves to a new stage (e.g., entering "documentation" creates a
      doc-collection checklist).
    </div>

    <ul v-else class="space-y-2">
      <li
        v-for="t in visibleTasks"
        :key="t.id"
        class="rounded-md border border-border bg-muted/40 p-2"
        :class="t.completed_at ? 'opacity-60' : ''"
      >
        <div class="flex flex-wrap items-baseline gap-2">
          <input
            type="checkbox"
            class="h-4 w-4 cursor-pointer accent-emerald-500"
            :checked="!!t.completed_at"
            :disabled="!!t.completed_at || !!submitting[t.id]"
            @change="complete(t)"
          />
          <p
            class="text-sm text-foreground"
            :class="t.completed_at ? 'line-through' : 'font-semibold'"
          >
            {{ t.title }}
          </p>
          <span
            v-if="t.auto_generated"
            class="rounded-full bg-primary/15 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-primary"
            :title="t.metadata?.to_stage ? `Auto-generated when deal moved to ${t.metadata.to_stage}` : 'Auto-generated by automation'"
          >
            auto
          </span>
          <span
            v-if="t.metadata?.priority === 'high'"
            class="rounded-full bg-warning/15 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-warning"
          >
            high
          </span>
          <span
            v-if="t.due_at"
            class="ml-auto text-xs"
            :class="dueClass(t)"
          >
            {{ dueLabel(t) }}
          </span>
        </div>
        <p
          v-if="t.description"
          class="ml-6 mt-1 text-xs text-foreground"
        >
          {{ t.description }}
        </p>
        <div
          v-if="!t.completed_at"
          class="ml-6 mt-2 flex flex-wrap gap-1"
        >
          <button
            type="button"
            class="rounded-md border border-border bg-background px-2 py-0.5 text-[11px] font-semibold text-foreground hover:bg-accent hover:text-accent-foreground disabled:opacity-50"
            :disabled="!!submitting[t.id]"
            @click="snooze(t, 1)"
          >
            +1d
          </button>
          <button
            type="button"
            class="rounded-md border border-border bg-background px-2 py-0.5 text-[11px] font-semibold text-foreground hover:bg-accent hover:text-accent-foreground disabled:opacity-50"
            :disabled="!!submitting[t.id]"
            @click="snooze(t, 3)"
          >
            +3d
          </button>
          <button
            type="button"
            class="rounded-md border border-border bg-background px-2 py-0.5 text-[11px] font-semibold text-foreground hover:bg-accent hover:text-accent-foreground disabled:opacity-50"
            :disabled="!!submitting[t.id]"
            @click="snooze(t, 7)"
          >
            +1w
          </button>
        </div>
      </li>
    </ul>
  </section>
</template>
