<script setup lang="ts">
/**
 * Admin broker-invitations management.
 *
 * Lists all broker invitation rows produced by broker imports
 * (mig 38) with their distribution + lifecycle state. Admin can:
 *   - Copy invitation link (stamps link_shared_at)
 *   - Filter by status
 *
 * Email automation deferred — admins distribute links manually for
 * v1 (paste in Slack, send from personal email, etc.).
 */
import { ref, computed, onMounted, watch } from 'vue'
import { showToast } from '~/helpers/helpers'

type Status = 'pending' | 'accepted' | 'declined' | 'expired'

type Invitation = {
  id: string
  email: string
  full_name: string | null
  org_role: string
  token: string
  status: Status
  effective_status: Status
  expires_at: string | null
  accepted_at: string | null
  declined_at: string | null
  link_shared_at: string | null
  email_sent_at: string | null
  created_at: string
  organization: { id: string; name: string; slug: string } | null
  branch: { id: string; name: string; slug: string } | null
  inviter: { id: string; full_name: string | null; email: string | null } | null
}

const status = ref<Status | ''>('pending')
const page = ref(1)
const pageSize = 20
const invitations = ref<Invitation[]>([])
const total = ref(0)
const loading = ref(true)
const submitting = ref<Record<string, boolean>>({})

async function load() {
  loading.value = true
  try {
    const query: Record<string, string | number> = { page: page.value, page_size: pageSize }
    if (status.value) query.status = status.value
    const res = await $fetch<{ invitations: Invitation[]; total: number }>(
      '/api/admin/brokers/invitations',
      { query },
    )
    invitations.value = res.invitations ?? []
    total.value = res.total ?? 0
  } catch (err: any) {
    showToast({
      title: err?.statusMessage || err?.message || 'Failed to load invitations',
      icon: 'error',
    })
  } finally {
    loading.value = false
  }
}

watch([status, page], load)
watch(status, () => { page.value = 1 })
onMounted(load)

function inviteUrl(token: string): string {
  if (typeof window === 'undefined') return `/invite/${token}`
  const origin = window.location.origin
  return `${origin}/invite/${token}`
}

async function copyLink(inv: Invitation) {
  if (submitting.value[inv.id]) return
  submitting.value[inv.id] = true
  try {
    const url = inviteUrl(inv.token)
    await navigator.clipboard.writeText(url)
    // Best-effort: stamp link_shared_at so the UI reflects distribution.
    await $fetch(`/api/admin/brokers/invitations/${inv.id}/mark-shared`, { method: 'POST' })
    showToast({ title: 'Link copied', icon: 'success' })
    await load()
  } catch (err: any) {
    showToast({
      title: err?.statusMessage || err?.message || 'Failed to copy link',
      icon: 'error',
    })
  } finally {
    delete submitting.value[inv.id]
  }
}

function statusBadge(s: Status): { label: string; cls: string } {
  switch (s) {
    case 'pending':  return { label: 'Pending',  cls: 'bg-warning/10 text-warning ring-warning/30' }
    case 'accepted': return { label: 'Accepted', cls: 'bg-success/10 text-success ring-success/30' }
    case 'declined': return { label: 'Declined', cls: 'bg-muted-foreground/10 text-muted-foreground ring-muted-foreground/15' }
    case 'expired':  return { label: 'Expired',  cls: 'bg-destructive/10 text-destructive ring-destructive/30' }
  }
}

const totalPages = computed(() => Math.max(1, Math.ceil(total.value / pageSize)))
</script>

<template>
  <section class="space-y-4">
    <header class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
      <div>
        <h2 class="text-base font-semibold text-foreground">Broker invitations</h2>
        <p class="mt-0.5 max-w-3xl text-xs text-muted-foreground">
          Generated by broker imports when the email doesn't match an
          existing profile. Copy the link and share it out-of-band —
          automated email is a follow-up turn.
        </p>
      </div>
      <div class="flex items-center gap-2">
        <label class="text-xs font-medium text-muted-foreground">Status</label>
        <select
          v-model="status"
          class="rounded-md border border-border bg-card px-2 py-1.5 text-xs text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
        >
          <option value="">All</option>
          <option value="pending">Pending</option>
          <option value="accepted">Accepted</option>
          <option value="declined">Declined</option>
          <option value="expired">Expired</option>
        </select>
        <span class="rounded-full bg-muted-foreground/10 px-2.5 py-1 text-xs font-semibold tabular-nums text-foreground/80">
          {{ total.toLocaleString() }}
        </span>
      </div>
    </header>

    <div v-if="loading" class="space-y-2">
      <div
        v-for="n in 4"
        :key="n"
        class="rounded-lg border border-border bg-card p-3"
      >
        <div class="flex items-baseline gap-2">
          <Skeleton class="h-4 w-16 rounded-full" />
          <Skeleton class="h-3 w-32" />
          <Skeleton class="h-3 w-40" />
        </div>
        <Skeleton class="mt-2 h-3 w-1/2" />
      </div>
    </div>

    <section
      v-else-if="invitations.length === 0"
      class="rounded-lg border border-border bg-card"
    >
      <EmptyState
        variant="neutral"
        size="cozy"
        title="No invitations with this filter"
        description="Broker imports generate invitations for unmatched emails. Adjust the status filter or run an import to populate this list."
      />
    </section>

    <ul v-else class="space-y-2">
      <li
        v-for="inv in invitations"
        :key="inv.id"
        class="rounded-lg border border-border bg-card p-3"
      >
        <div class="flex flex-wrap items-baseline gap-2">
          <span
            class="rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ring-1"
            :class="statusBadge(inv.effective_status).cls"
          >
            {{ statusBadge(inv.effective_status).label }}
          </span>
          <p class="text-sm font-semibold text-foreground">
            {{ inv.full_name || inv.email }}
          </p>
          <p class="font-mono text-[11px] text-muted-foreground">{{ inv.email }}</p>
          <p class="text-[11px] text-muted-foreground">
            → {{ inv.organization?.name }}<span v-if="inv.branch"> / {{ inv.branch.name }}</span>
            ·
            <span class="font-mono">{{ inv.org_role }}</span>
          </p>
          <p class="ml-auto text-[10px] text-muted-foreground">
            sent {{ new Date(inv.created_at).toLocaleDateString() }}
            <span v-if="inv.accepted_at" class="text-success">
              · accepted {{ new Date(inv.accepted_at).toLocaleDateString() }}
            </span>
            <span v-else-if="inv.declined_at" class="text-muted-foreground">
              · declined {{ new Date(inv.declined_at).toLocaleDateString() }}
            </span>
          </p>
        </div>

        <div class="mt-2 flex flex-wrap items-center gap-2 text-[11px]">
          <span
            v-if="inv.link_shared_at"
            class="rounded-full bg-primary/10 px-2 py-0.5 font-medium text-primary ring-1 ring-primary/30"
          >
            link shared {{ new Date(inv.link_shared_at).toLocaleDateString() }}
          </span>
          <span
            v-else
            class="rounded-full bg-muted-foreground/10 px-2 py-0.5 font-medium text-muted-foreground ring-1 ring-muted-foreground/15"
          >
            link not yet distributed
          </span>
          <button
            v-if="inv.effective_status === 'pending'"
            type="button"
            class="ml-auto rounded-lg bg-primary px-2.5 py-1 text-[11px] font-semibold text-white transition-colors hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-60"
            :disabled="submitting[inv.id]"
            @click="copyLink(inv)"
          >
            Copy invitation link
          </button>
        </div>
      </li>
    </ul>

    <div v-if="totalPages > 1" class="flex items-center justify-between text-xs">
      <p class="tabular-nums text-muted-foreground">
        Page {{ page }} of {{ totalPages }} · {{ total.toLocaleString() }} total
      </p>
      <div class="flex gap-1">
        <button
          type="button"
          class="rounded-lg border border-border bg-card px-3 py-1.5 font-medium text-foreground transition-colors hover:bg-accent disabled:cursor-not-allowed disabled:opacity-60"
          :disabled="page <= 1"
          @click="page = page - 1"
        >
          ← Previous
        </button>
        <button
          type="button"
          class="rounded-lg border border-border bg-card px-3 py-1.5 font-medium text-foreground transition-colors hover:bg-accent disabled:cursor-not-allowed disabled:opacity-60"
          :disabled="page >= totalPages"
          @click="page = page + 1"
        >
          Next →
        </button>
      </div>
    </div>
  </section>
</template>
