/**
 * Saved-search confirmation handler.
 *
 * GET /api/public/saved-searches/confirm/<token>
 *
 * Hit from the link in the confirmation email. Flips
 * `confirmed_at = now()` on first valid call; idempotent re-clicks
 * succeed silently. Returns a minimal HTML page so the user lands on
 * a real "thank you" rather than raw JSON.
 *
 * Token is the value generated by `generate_saved_search_token()`
 * (64 hex chars, 256 bits entropy). UNIQUE-indexed.
 *
 * Wrong / expired / unknown token → 404 with HTML page. We don't
 * differentiate "wrong token" from "no such row" to avoid timing /
 * existence leaks.
 */
import { getServerSupabaseAdmin } from '~~/server/utils/supabase'
import { logger } from '~~/server/utils/logger'

const TOKEN_RE = /^[0-9a-f]{32,128}$/i

function htmlPage(opts: { title: string; body: string; status: number }) {
  return `<!doctype html>
<html lang="en"><head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${opts.title}</title>
  <style>
    body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:#f6f7fa;color:#1f2937}
    .wrap{max-width:560px;margin:80px auto;padding:32px;background:#fff;border:1px solid #e5e7eb;border-radius:12px}
    h1{margin:0 0 12px;font-size:20px;color:#111827}
    p{margin:0 0 12px;line-height:1.5}
    a{color:#2563eb}
  </style>
</head>
<body>
  <div class="wrap">
    <h1>${opts.title}</h1>
    ${opts.body}
  </div>
</body></html>`
}

export default defineEventHandler(async (event) => {
  setHeader(event, 'content-type', 'text/html; charset=utf-8')
  setHeader(event, 'cache-control', 'private, no-store')

  const token = getRouterParam(event, 'token')

  if (!token || !TOKEN_RE.test(token)) {
    setResponseStatus(event, 404)
    return htmlPage({
      status: 404,
      title: 'Link not recognized',
      body: '<p>That confirmation link doesn\'t look right. Please use the most recent confirmation email we sent you.</p>',
    })
  }

  const admin = getServerSupabaseAdmin()

  // Idempotent: only flip confirmed_at if it's still NULL. Re-clicks
  // return the same "confirmed" page silently.
  const { data, error } = await (admin as any)
    .from('saved_search_subscriptions')
    .update({ confirmed_at: new Date().toISOString() })
    .eq('confirmation_token', token)
    .is('confirmed_at', null)
    .select('id, name, email')
    .maybeSingle()

  if (error) {
    logger.error(
      { err: error.message, op: 'saved_searches.confirm' },
      'saved_search_confirm_failed',
    )
    setResponseStatus(event, 500)
    return htmlPage({
      status: 500,
      title: 'Something went wrong',
      body: '<p>We couldn\'t confirm your subscription right now. Please try clicking the link again in a few minutes.</p>',
    })
  }

  if (data) {
    return htmlPage({
      status: 200,
      title: 'Subscription confirmed',
      body:
        `<p>Thanks${data.name ? `, ${escapeHtml(data.name)}` : ''} — you'll start getting digest emails of new matching listings.</p>` +
        '<p>You can unsubscribe at any time from the link at the bottom of any digest email.</p>',
    })
  }

  // No row updated. Either the token is unknown OR the subscription
  // was already confirmed. Treat both as success — looks identical to
  // a re-click.
  const { data: existing } = await (admin as any)
    .from('saved_search_subscriptions')
    .select('id')
    .eq('confirmation_token', token)
    .maybeSingle()

  if (existing) {
    return htmlPage({
      status: 200,
      title: 'Already confirmed',
      body: '<p>This subscription is already confirmed. You\'ll get digest emails when new matching listings come online.</p>',
    })
  }

  setResponseStatus(event, 404)
  return htmlPage({
    status: 404,
    title: 'Link not recognized',
    body: '<p>That confirmation link is no longer valid. If you still want to subscribe, please save the search again.</p>',
  })
})

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}
