-- Workflow Automation + Smart Operations.
--
-- Lightweight, deterministic automation layer. NO DSL, NO AI:
-- the rules are seeded SQL templates that fire on deal stage
-- transitions; SLA breaches and recommendations are derived views.
--
-- Three additive objects:
--   1. public.tasks gets `deal_id`, `auto_generated`,
--      `last_reminder_sent_at` columns (additive only)
--   2. public.automation_task_templates — seeded rule registry
--   3. public.pipeline_alerts (view) — SLA / stale-state alerts
--   4. public.pipeline_recommendations (view) — next-action hints
--
-- Plus: trigger on deals UPDATE that materializes templates into
-- tasks rows; daily reminder cron that fires notifications for
-- approaching due dates.
--
-- ROLLBACK:
--   SELECT cron.unschedule('tasks_reminder_daily');
--   DROP VIEW IF EXISTS public.pipeline_recommendations;
--   DROP VIEW IF EXISTS public.pipeline_alerts;
--   DROP TRIGGER IF EXISTS deals_apply_task_templates ON public.deals;
--   DROP FUNCTION IF EXISTS public.deals_apply_task_templates_fn();
--   DROP TABLE IF EXISTS public.automation_task_templates;
--   ALTER TABLE public.tasks DROP COLUMN IF EXISTS last_reminder_sent_at;
--   ALTER TABLE public.tasks DROP COLUMN IF EXISTS auto_generated;
--   ALTER TABLE public.tasks DROP COLUMN IF EXISTS deal_id;


-- =====================================================================
-- 1. tasks — additive columns
-- =====================================================================

ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS deal_id uuid REFERENCES public.deals(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS auto_generated boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS last_reminder_sent_at timestamptz;

-- Hot indexes for the workflow inbox + reminder cron:
CREATE INDEX IF NOT EXISTS tasks_deal_idx
  ON public.tasks(deal_id) WHERE deal_id IS NOT NULL;
-- "due in next 24h, not yet reminded" — the reminder cron's only
-- query. Partial index keeps the working set tiny.
CREATE INDEX IF NOT EXISTS tasks_due_reminder_idx
  ON public.tasks(due_at)
  WHERE due_at IS NOT NULL
    AND completed_at IS NULL
    AND last_reminder_sent_at IS NULL;
-- "open tasks for assignee" — dashboard widget query.
CREATE INDEX IF NOT EXISTS tasks_assignee_open_idx
  ON public.tasks(assigned_to_user_id, due_at)
  WHERE completed_at IS NULL;

COMMENT ON COLUMN public.tasks.deal_id IS
  'Optional FK to deals. When set, the task is part of a deal workflow (auto-generated by stage transitions or manually attached). RLS inherits via deal participation when set.';
COMMENT ON COLUMN public.tasks.auto_generated IS
  'true when the task was created by automation_task_templates trigger. UI surfaces this so operators see "auto-created when deal moved to documentation" rather than mystery tasks.';


-- =====================================================================
-- 2. automation_task_templates — seeded rule registry
-- =====================================================================
--
-- Each row defines one rule: "when <trigger_event> matches
-- <trigger_match>, create a task with <task_template>".
--
-- Trigger events supported (free-form text — operators can extend):
--   deal.stage_changed  trigger_match: { to_stage: '<stage_key>' }
--
-- task_template jsonb:
--   { title: string, description?: string, due_offset_hours: int,
--     priority?: string }
--
-- One rule can spawn one task per deal stage transition. To spawn
-- multiple (e.g., a documentation checklist), seed multiple rules
-- with the same trigger_match.

CREATE TABLE IF NOT EXISTS public.automation_task_templates (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  trigger_event   text NOT NULL CHECK (trigger_event IN (
                       'deal.stage_changed'
                     )),
  trigger_match   jsonb NOT NULL DEFAULT '{}'::jsonb,
  task_template   jsonb NOT NULL,
  enabled         boolean NOT NULL DEFAULT true,
  description     text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS automation_task_templates_trigger_idx
  ON public.automation_task_templates(trigger_event)
  WHERE enabled = true;

DROP TRIGGER IF EXISTS set_automation_task_templates_updated_at
  ON public.automation_task_templates;
CREATE TRIGGER set_automation_task_templates_updated_at
  BEFORE UPDATE ON public.automation_task_templates
  FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();

ALTER TABLE public.automation_task_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS automation_task_templates_select ON public.automation_task_templates;
CREATE POLICY automation_task_templates_select
  ON public.automation_task_templates FOR SELECT
  TO authenticated USING (true);
-- INSERT/UPDATE/DELETE: service-role only. Operators add rules via
-- SQL until a config UI ships.

COMMENT ON TABLE public.automation_task_templates IS
  'Seeded rule registry for deterministic task auto-generation. trigger_event + trigger_match define when; task_template defines what. Service-role-only writes (no DSL UI v1).';

-- Seed the standard pipeline workflows.
INSERT INTO public.automation_task_templates (trigger_event, trigger_match, task_template, description) VALUES
  ('deal.stage_changed',
   '{"to_stage":"contacted"}'::jsonb,
   jsonb_build_object(
     'title', 'Follow up with buyer within 24h',
     'description', 'Initial contact made; confirm interest level and gather requirements.',
     'due_offset_hours', 24,
     'priority', 'high'
   ),
   'On contacted: 24h follow-up reminder for the buyer agent.'),

  ('deal.stage_changed',
   '{"to_stage":"viewing_scheduled"}'::jsonb,
   jsonb_build_object(
     'title', 'Confirm viewing logistics',
     'description', 'Confirm time/place with buyer and seller; arrange access if needed.',
     'due_offset_hours', 12,
     'priority', 'medium'
   ),
   'On viewing_scheduled: confirm logistics 12h ahead.'),

  ('deal.stage_changed',
   '{"to_stage":"viewing_completed"}'::jsonb,
   jsonb_build_object(
     'title', 'Follow up with client after viewing',
     'description', 'Capture feedback while fresh; record buyer interest level.',
     'due_offset_hours', 24,
     'priority', 'high'
   ),
   'On viewing_completed: 24h post-view follow-up.'),

  ('deal.stage_changed',
   '{"to_stage":"negotiating"}'::jsonb,
   jsonb_build_object(
     'title', 'Document negotiation positions',
     'description', 'Note current offer/counter, contingencies, and decision deadlines.',
     'due_offset_hours', 48,
     'priority', 'medium'
   ),
   'On negotiating: capture positions within 48h.'),

  ('deal.stage_changed',
   '{"to_stage":"reservation"}'::jsonb,
   jsonb_build_object(
     'title', 'Collect reservation agreement',
     'description', 'Upload signed reservation agreement to deal documents.',
     'due_offset_hours', 72,
     'priority', 'high'
   ),
   'On reservation: collect signed agreement within 72h.'),

  -- Documentation stage spawns multiple checklist tasks.
  ('deal.stage_changed',
   '{"to_stage":"documentation"}'::jsonb,
   jsonb_build_object(
     'title', 'Collect Letter of Intent (LOI)',
     'description', 'Signed LOI from buyer.',
     'due_offset_hours', 168,
     'priority', 'high'
   ),
   'On documentation: LOI checklist task.'),
  ('deal.stage_changed',
   '{"to_stage":"documentation"}'::jsonb,
   jsonb_build_object(
     'title', 'Collect government-issued IDs',
     'description', '2 valid IDs from buyer + seller.',
     'due_offset_hours', 168,
     'priority', 'high'
   ),
   'On documentation: IDs checklist task.'),
  ('deal.stage_changed',
   '{"to_stage":"documentation"}'::jsonb,
   jsonb_build_object(
     'title', 'Collect proof of payment / earnest money',
     'description', 'Receipt or bank confirmation of earnest money deposit.',
     'due_offset_hours', 168,
     'priority', 'high'
   ),
   'On documentation: earnest-money checklist task.'),
  ('deal.stage_changed',
   '{"to_stage":"documentation"}'::jsonb,
   jsonb_build_object(
     'title', 'Collect contract to sell',
     'description', 'Signed CTS from both parties.',
     'due_offset_hours', 336,
     'priority', 'medium'
   ),
   'On documentation: CTS checklist task.'),

  ('deal.stage_changed',
   '{"to_stage":"financing"}'::jsonb,
   jsonb_build_object(
     'title', 'Track financing approval',
     'description', 'Check in with buyer on bank approval timeline; collect supporting docs.',
     'due_offset_hours', 168,
     'priority', 'medium'
   ),
   'On financing: weekly check-in on financing.'),

  ('deal.stage_changed',
   '{"to_stage":"closing"}'::jsonb,
   jsonb_build_object(
     'title', 'Coordinate closing date',
     'description', 'Confirm closing logistics with buyer, seller, and bank if applicable.',
     'due_offset_hours', 72,
     'priority', 'high'
   ),
   'On closing: coordinate closing within 72h.'),
  ('deal.stage_changed',
   '{"to_stage":"closing"}'::jsonb,
   jsonb_build_object(
     'title', 'Final walk-through',
     'description', 'Schedule and conduct final walk-through with buyer.',
     'due_offset_hours', 168,
     'priority', 'medium'
   ),
   'On closing: final walk-through reminder.')
ON CONFLICT DO NOTHING;


-- =====================================================================
-- 3. Trigger — materialize templates into tasks on stage change
-- =====================================================================
--
-- AFTER UPDATE on deals.stage_key — fires only on actual transitions
-- (NEW.stage_key IS DISTINCT FROM OLD.stage_key).
--
-- For each enabled template matching `deal.stage_changed` +
-- to_stage = NEW.stage_key, INSERT a task assigned to the deal's
-- buyer_agent_user_id (or created_by as fallback).
--
-- auto_generated = true so the UI can render "auto-created" badging.
-- metadata holds the template id so operators can trace back.

CREATE OR REPLACE FUNCTION public.deals_apply_task_templates_fn()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  tpl RECORD;
  v_assignee uuid;
  v_due timestamptz;
BEGIN
  -- Only fire on actual stage changes, not other deal updates.
  IF NEW.stage_key IS NOT DISTINCT FROM OLD.stage_key THEN
    RETURN NEW;
  END IF;

  -- Don't fire on terminal states — closing a deal shouldn't spawn
  -- new follow-up tasks.
  IF NEW.stage_key IN ('closed_won', 'closed_lost') THEN
    RETURN NEW;
  END IF;

  v_assignee := COALESCE(NEW.buyer_agent_user_id, NEW.created_by);
  IF v_assignee IS NULL THEN
    -- No one to assign to; skip rather than orphan tasks.
    RETURN NEW;
  END IF;

  FOR tpl IN
    SELECT id, task_template
      FROM public.automation_task_templates
     WHERE enabled = true
       AND trigger_event = 'deal.stage_changed'
       AND trigger_match->>'to_stage' = NEW.stage_key
  LOOP
    v_due := now() + ((tpl.task_template->>'due_offset_hours')::int * interval '1 hour');

    INSERT INTO public.tasks (
      title,
      description,
      due_at,
      assigned_to_user_id,
      deal_id,
      auto_generated,
      metadata
    )
    VALUES (
      tpl.task_template->>'title',
      tpl.task_template->>'description',
      v_due,
      v_assignee,
      NEW.id,
      true,
      jsonb_build_object(
        'template_id', tpl.id,
        'trigger_event', 'deal.stage_changed',
        'to_stage', NEW.stage_key,
        'priority', tpl.task_template->>'priority'
      )
    );
  END LOOP;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS deals_apply_task_templates ON public.deals;
CREATE TRIGGER deals_apply_task_templates
  AFTER UPDATE OF stage_key ON public.deals
  FOR EACH ROW EXECUTE FUNCTION public.deals_apply_task_templates_fn();

COMMENT ON FUNCTION public.deals_apply_task_templates_fn() IS
  'Materializes automation_task_templates into tasks rows on deal stage transitions. Fires once per matching template; assigns to buyer_agent_user_id (fallback created_by). auto_generated=true tags rows so the UI can distinguish from manual tasks.';


-- =====================================================================
-- 4. pipeline_alerts view — SLA / stale-state breaches
-- =====================================================================
--
-- Mirrors the ops_alerts view's pattern but for OPERATOR workflows.
-- Pure derived; no backing storage. Each branch is an independent
-- SELECT unioned with consistent shape.
--
-- Severity: critical / warning / info.

CREATE OR REPLACE VIEW public.pipeline_alerts AS
SELECT *
  FROM (
    -- Inquiries unanswered > 24h
    SELECT
      'inquiry.unanswered.' || i.id::text                          AS key,
      'warning'                                                    AS severity,
      'inquiry'                                                    AS category,
      i.assigned_user_id                                           AS owner_user_id,
      'Inquiry unanswered for ' ||
        EXTRACT(EPOCH FROM now() - i.created_at)::int / 3600 || 'h' AS title,
      'Sender: ' || i.sender_name                                  AS detail,
      jsonb_build_object(
        'inquiry_id', i.id,
        'listing_id', i.listing_id,
        'sender_name', i.sender_name,
        'hours_since_received', EXTRACT(EPOCH FROM now() - i.created_at)::int / 3600
      )                                                            AS metadata,
      i.created_at                                                 AS started_at
      FROM public.inquiries i
     WHERE i.status = 'new'
       AND i.assigned_user_id IS NOT NULL
       AND now() - i.created_at > interval '24 hours'

    UNION ALL

    -- Deals stuck in their current stage > 7 days (excluding terminal)
    SELECT
      'deal.stale.' || d.id::text,
      CASE
        WHEN now() - d.stage_entered_at > interval '14 days' THEN 'critical'
        ELSE 'warning'
      END,
      'deal',
      d.buyer_agent_user_id,
      'Deal stuck in ' || d.stage_key || ' for ' ||
        EXTRACT(EPOCH FROM now() - d.stage_entered_at)::int / 86400 || 'd',
      COALESCE(d.title, 'Deal ' || d.id::text),
      jsonb_build_object(
        'deal_id', d.id,
        'listing_id', d.listing_id,
        'stage_key', d.stage_key,
        'days_in_stage', EXTRACT(EPOCH FROM now() - d.stage_entered_at)::int / 86400
      ),
      d.stage_entered_at
      FROM public.deals d
     WHERE d.closed_at IS NULL
       AND d.stage_key NOT IN ('closed_won', 'closed_lost')
       AND now() - d.stage_entered_at > interval '7 days'

    UNION ALL

    -- Viewings scheduled but not marked complete >2h after end-time
    SELECT
      'viewing.unupdated.' || v.id::text,
      'warning',
      'viewing',
      v.attending_user_id,
      'Viewing not marked complete',
      'Scheduled ' || v.scheduled_at::text || '; status still "scheduled"',
      jsonb_build_object(
        'viewing_id', v.id,
        'deal_id', v.deal_id,
        'scheduled_at', v.scheduled_at
      ),
      v.scheduled_at
      FROM public.deal_viewings v
     WHERE v.status = 'scheduled'
       AND v.scheduled_at + (v.duration_minutes * interval '1 minute')
           + interval '2 hours' < now()

    UNION ALL

    -- Documentation-stage deals with too few documents (heuristic
    -- v1: <3 means likely missing essentials)
    SELECT
      'deal.docs_thin.' || d.id::text,
      'info',
      'deal',
      d.buyer_agent_user_id,
      'Documentation stage but only '
        || (SELECT count(*) FROM public.documents WHERE deal_id = d.id)::text
        || ' docs uploaded',
      COALESCE(d.title, 'Deal ' || d.id::text),
      jsonb_build_object(
        'deal_id', d.id,
        'listing_id', d.listing_id,
        'doc_count', (SELECT count(*) FROM public.documents WHERE deal_id = d.id)
      ),
      d.stage_entered_at
      FROM public.deals d
     WHERE d.closed_at IS NULL
       AND d.stage_key = 'documentation'
       AND (SELECT count(*) FROM public.documents WHERE deal_id = d.id) < 3
       AND now() - d.stage_entered_at > interval '3 days'

    UNION ALL

    -- Reservation deals open >30 days (over a typical reservation window)
    SELECT
      'deal.reservation_expired.' || d.id::text,
      'warning',
      'deal',
      d.buyer_agent_user_id,
      'Reservation older than 30 days — confirm or release',
      COALESCE(d.title, 'Deal ' || d.id::text),
      jsonb_build_object(
        'deal_id', d.id,
        'listing_id', d.listing_id,
        'days_in_reservation', EXTRACT(EPOCH FROM now() - d.stage_entered_at)::int / 86400
      ),
      d.stage_entered_at
      FROM public.deals d
     WHERE d.closed_at IS NULL
       AND d.stage_key = 'reservation'
       AND now() - d.stage_entered_at > interval '30 days'
  ) AS u
ORDER BY
  CASE severity WHEN 'critical' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END,
  started_at DESC;

GRANT SELECT ON public.pipeline_alerts TO authenticated;

COMMENT ON VIEW public.pipeline_alerts IS
  'Operator-side SLA / stale-state alerts. Mirror of ops_alerts but for broker workflows. Always fresh; no backing storage. Each row carries owner_user_id so the dashboard can scope to "my alerts".';


-- =====================================================================
-- 5. pipeline_recommendations view — next-action hints per deal
-- =====================================================================

CREATE OR REPLACE VIEW public.pipeline_recommendations AS
SELECT *
  FROM (
    -- viewing_completed → suggest negotiating after 3 days of inactivity
    SELECT
      d.id                                            AS deal_id,
      d.listing_id,
      d.buyer_agent_user_id,
      'suggest_advance_to_negotiating'                AS rule_key,
      'Move to negotiating?'                          AS title,
      'Viewing completed ' ||
        EXTRACT(EPOCH FROM now() - d.stage_entered_at)::int / 86400
        || ' days ago; if buyer is interested, advance the stage.' AS detail,
      jsonb_build_object('to_stage', 'negotiating')   AS suggested_action
      FROM public.deals d
     WHERE d.closed_at IS NULL
       AND d.stage_key = 'viewing_completed'
       AND now() - d.stage_entered_at > interval '3 days'

    UNION ALL

    -- negotiating → suggest reservation or check-in after 7 days
    SELECT
      d.id, d.listing_id, d.buyer_agent_user_id,
      'suggest_check_in_negotiation',
      'Check in on negotiation',
      'Negotiating for ' ||
        EXTRACT(EPOCH FROM now() - d.stage_entered_at)::int / 86400
        || ' days; check in to confirm offer is still active.',
      jsonb_build_object('action', 'create_followup_task')
      FROM public.deals d
     WHERE d.closed_at IS NULL
       AND d.stage_key = 'negotiating'
       AND now() - d.stage_entered_at > interval '7 days'

    UNION ALL

    -- documentation → suggest specific missing doc types
    SELECT
      d.id, d.listing_id, d.buyer_agent_user_id,
      'suggest_request_missing_docs',
      'Request missing documents',
      'Documentation stage but only '
        || (SELECT count(*) FROM public.documents WHERE deal_id = d.id)::text
        || ' docs attached. Common deal docs: LOI, IDs, proof of payment, contract.',
      jsonb_build_object(
        'doc_count', (SELECT count(*) FROM public.documents WHERE deal_id = d.id)
      )
      FROM public.deals d
     WHERE d.closed_at IS NULL
       AND d.stage_key = 'documentation'
       AND (SELECT count(*) FROM public.documents WHERE deal_id = d.id) < 4

    UNION ALL

    -- reservation → suggest advance to documentation after 7 days
    SELECT
      d.id, d.listing_id, d.buyer_agent_user_id,
      'suggest_advance_to_documentation',
      'Move to documentation?',
      'Reservation has been ' ||
        EXTRACT(EPOCH FROM now() - d.stage_entered_at)::int / 86400
        || ' days; if signed, move to documentation to track contracts.',
      jsonb_build_object('to_stage', 'documentation')
      FROM public.deals d
     WHERE d.closed_at IS NULL
       AND d.stage_key = 'reservation'
       AND now() - d.stage_entered_at > interval '7 days'
  ) AS r;

GRANT SELECT ON public.pipeline_recommendations TO authenticated;

COMMENT ON VIEW public.pipeline_recommendations IS
  'Deterministic next-action hints per deal. Pure SQL; no ML. Each row has an explainable rule_key the UI can render alongside the suggestion.';


-- =====================================================================
-- 6. Daily reminder cron — fires notifications for due-soon tasks
-- =====================================================================
--
-- Runs at 07:00 UTC daily. Scans tasks due within 24h that haven't
-- been reminded yet. For each, inserts a notification + stamps
-- last_reminder_sent_at so re-runs are no-ops.
--
-- This is a SQL-only cron (no HTTP call). Notifications insert
-- directly into public.notifications. Email fan-out would require
-- the application-side notify() helper; a future iteration can
-- replace this with an HTTP-call cron if email-on-reminder is
-- needed. v1 covers in-app bell only.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    RAISE NOTICE 'pg_cron not installed; tasks_reminder cron NOT scheduled.';
    RETURN;
  END IF;

  PERFORM cron.unschedule('tasks_reminder_daily')
    WHERE EXISTS (
      SELECT 1 FROM cron.job WHERE jobname = 'tasks_reminder_daily'
    );

  PERFORM cron.schedule(
    'tasks_reminder_daily',
    '0 7 * * *',
    $cmd$
      WITH due AS (
        SELECT id, title, due_at, assigned_to_user_id, deal_id, listing_id
          FROM public.tasks
         WHERE due_at IS NOT NULL
           AND due_at BETWEEN now() AND now() + interval '24 hours'
           AND completed_at IS NULL
           AND last_reminder_sent_at IS NULL
           AND assigned_to_user_id IS NOT NULL
         LIMIT 500
      ),
      inserted AS (
        INSERT INTO public.notifications (
          recipient_user_id, kind, title, body, href, metadata, created_at
        )
        SELECT
          assigned_to_user_id,
          'task.due_soon',
          'Task due within 24h: ' || title,
          'Due ' || to_char(due_at, 'Mon DD HH24:MI'),
          CASE WHEN deal_id IS NOT NULL THEN '/deals/' || deal_id::text
               ELSE '/tasks' END,
          jsonb_build_object('task_id', id, 'deal_id', deal_id),
          now()
          FROM due
        RETURNING (metadata->>'task_id')::uuid AS task_id
      )
      UPDATE public.tasks
         SET last_reminder_sent_at = now()
       WHERE id IN (SELECT task_id FROM inserted);
    $cmd$
  );
END $$;


NOTIFY pgrst, 'reload schema';
