-- Saved-search subscriptions for the public marketplace.
--
-- Anonymous (no auth required): visitors enter their email + a search
-- filter set; the system stores it server-side and (in a future round)
-- emails them a digest of new matches on a schedule.
--
-- Wire-format parity with the existing public-form pattern:
--   POST /api/public/inquiries     → service-role insert, no anon RLS
--   POST /api/public/saved-searches → same pattern
--
-- Double-opt-in: confirmed_at IS NULL until the user clicks the
-- confirmation link in their email. Cron worker (future) only fans
-- out digests to confirmed rows. Bad actors signing up someone else's
-- email therefore can't trigger non-confirmation traffic.
--
-- Two tokens per row:
--   - confirmation_token  → flips confirmed_at on first click
--   - unsubscribe_token   → hard-deletes the row on click
-- Both are 32-byte random hex (256 bits entropy) generated by Postgres,
-- never sent to the client API response — only via email.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS public.saved_search_subscriptions CASCADE;
--   DROP FUNCTION IF EXISTS public.generate_saved_search_token();
--
-- DEPENDS ON:
--   20260429000001_create_profiles_table.sql (set_current_timestamp_updated_at)


-- =====================================================================
-- 1. Token generator
-- =====================================================================
--
-- 32 bytes → 64 hex chars. Same approach used elsewhere in this repo
-- (document-drafts share tokens, e.g.). Wrapped in a SECURITY DEFINER
-- function so the table DEFAULT can call it without callers needing
-- pgcrypto privileges.

CREATE OR REPLACE FUNCTION public.generate_saved_search_token()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN encode(gen_random_bytes(32), 'hex');
END
$$;

REVOKE ALL ON FUNCTION public.generate_saved_search_token() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.generate_saved_search_token() TO service_role;


-- =====================================================================
-- 2. Table
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.saved_search_subscriptions (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Subscriber identity (no FK to auth.users — these are public-marketplace
  -- visitors who haven't signed up). Email is normalized to lowercase
  -- application-side before insert.
  email             text NOT NULL,
  -- Optional human-readable name for the search ("Makati 2BR rentals").
  name              text,

  -- Search filter set. Schema is application-defined (see the POST
  -- endpoint's Zod for the current shape). Stored as jsonb so the
  -- digest worker can query subsets via -> / @> when filtering listings.
  filters           jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- 'daily' | 'weekly' for now. Add 'instant' later without a migration
  -- by relaxing the CHECK; current cron worker (future) will only
  -- handle daily / weekly.
  digest_frequency  text NOT NULL DEFAULT 'weekly'
    CHECK (digest_frequency IN ('daily', 'weekly')),

  -- Tokens. UNIQUE-indexed; values inserted via DEFAULT so callers
  -- (server endpoints) never need to mint them themselves.
  confirmation_token text NOT NULL DEFAULT public.generate_saved_search_token(),
  unsubscribe_token  text NOT NULL DEFAULT public.generate_saved_search_token(),

  -- State.
  -- confirmed_at IS NULL → pending; the cron worker skips it.
  confirmed_at         timestamptz,
  -- last_digest_sent_at lets the worker compute "new matches since".
  -- Initially NULL; on the first digest run, set to the run timestamp.
  last_digest_sent_at  timestamptz,

  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS saved_search_subscriptions_email_idx
  ON public.saved_search_subscriptions(email);

-- Hot path: cron worker pulling confirmed, ready-for-digest rows.
CREATE INDEX IF NOT EXISTS saved_search_subscriptions_due_idx
  ON public.saved_search_subscriptions(confirmed_at, last_digest_sent_at, digest_frequency)
  WHERE confirmed_at IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS saved_search_subscriptions_confirm_token_idx
  ON public.saved_search_subscriptions(confirmation_token);

CREATE UNIQUE INDEX IF NOT EXISTS saved_search_subscriptions_unsub_token_idx
  ON public.saved_search_subscriptions(unsubscribe_token);

DROP TRIGGER IF EXISTS set_saved_search_subscriptions_updated_at
  ON public.saved_search_subscriptions;
CREATE TRIGGER set_saved_search_subscriptions_updated_at
  BEFORE UPDATE ON public.saved_search_subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();

COMMENT ON TABLE public.saved_search_subscriptions IS
  'Public-marketplace saved searches. Anonymous (email-keyed). Double-opt-in via confirmation_token. RLS enabled with no anon/authenticated policies — all access via service-role through /api/public/saved-searches/* endpoints.';


-- =====================================================================
-- 3. RLS
-- =====================================================================
--
-- Enabled but no policies. Direct REST calls (anon or authenticated)
-- return zero rows / refuse writes. The portal endpoints use the
-- service-role client to bypass RLS; the website proxy in a future
-- round forwards to those.

ALTER TABLE public.saved_search_subscriptions ENABLE ROW LEVEL SECURITY;


NOTIFY pgrst, 'reload schema';
