/**
 * Supabase-generated TypeScript schema types. Regenerated by `pnpm db:types`
 * (uses the Supabase CLI; see supabase/MIGRATIONS.md).
 *
 * The placeholder below keeps the file importable before the first generation
 * run. Once generated, this file will contain the full Database type with
 * every public.* table, view, and function. Don't hand-edit it.
 *
 * Usage:
 *   import type { Database } from '~~/server/utils/database.types'
 *   const client = await serverSupabaseClient<Database>(event)
 *   // client.from('listings').select(...) is fully typed.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
