<script setup lang="ts">
/**
 * Finalized-document panel for /document-drafts/[id].
 *
 * The broker workflow: print the draft → notarize + tax-stamp offline
 * → scan the result → upload the PDF here. The upload posts to
 * POST /api/document-drafts/:id/upload-signed which:
 *   1. stores the PDF in S3
 *   2. records the pointer in draft.data._finalized_document
 *   3. auto-transitions status from draft|in_review → signed
 *
 * Empty state surfaces a file picker. Filled state shows the on-file
 * PDF with size, original filename, upload time, view link, and a
 * "Replace" affordance for re-uploading a corrected scan.
 *
 * The signed download URL is generated by the upload endpoint and is
 * good for ~1 hour. We re-mint it via /api/document-drafts/:id/url
 * when the broker clicks "View" on a row that has a stale URL.
 */
import { ref, computed } from 'vue'
import { showToast } from '~/helpers/helpers'

type FinalizedDoc = {
  path: string
  uploaded_at: string
  original_filename: string | null
  byte_length?: number | null
}

type Draft = {
  id: string
  status: 'draft' | 'in_review' | 'signed' | 'archived'
  data?: { _finalized_document?: FinalizedDoc | null } | null
}

const props = defineProps<{
  draft: Draft
}>()

const emit = defineEmits<{
  (e: 'updated', draft: Partial<Draft>): void
}>()

const fileInputRef = ref<HTMLInputElement | null>(null)
const isUploading = ref(false)
const uploadProgress = ref<string>('')

const finalized = computed<FinalizedDoc | null>(
  () => props.draft.data?._finalized_document ?? null,
)

function formatSize(bytes: number | null | undefined): string {
  if (!bytes || !Number.isFinite(bytes)) return ''
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`
}

function formatTs(iso: string): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return iso
  return d.toLocaleString(undefined, {
    month: 'short', day: 'numeric', year: 'numeric',
    hour: 'numeric', minute: '2-digit',
  })
}

function pickFile() {
  fileInputRef.value?.click()
}

function fileToDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(String(reader.result ?? ''))
    reader.onerror = () => reject(reader.error || new Error('FileReader failed'))
    reader.readAsDataURL(file)
  })
}

async function onFileChange(e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0]
  // Reset so re-picking the same file fires `change` again.
  input.value = ''
  if (!file) return

  if (file.type !== 'application/pdf') {
    showToast({ title: 'Pick a PDF file (the notarized scan).', icon: 'warning' })
    return
  }
  // 25 MB raw — covers most notarized scans. The endpoint enforces
  // its own 33 MB base64 cap (~25 MB raw); fail fast here for UX.
  if (file.size > 25 * 1024 * 1024) {
    showToast({
      title: `File is ${(file.size / 1024 / 1024).toFixed(1)} MB. Max is 25 MB — re-scan at lower resolution.`,
      icon: 'warning',
    })
    return
  }

  isUploading.value = true
  uploadProgress.value = `Encoding ${file.name}…`
  try {
    const dataUrl = await fileToDataUrl(file)
    uploadProgress.value = `Uploading…`
    const res = await $fetch<{
      path: string
      original_filename: string | null
      byte_length: number
      status: Draft['status']
      transitioned: boolean
    }>(`/api/document-drafts/${props.draft.id}/upload-signed`, {
      method: 'POST',
      body: {
        data_url: dataUrl,
        filename: file.name,
      },
    })
    showToast({
      title: res.transitioned
        ? 'Notarized PDF uploaded — head to the related deal to start the transfer workflow.'
        : 'Notarized PDF uploaded.',
      icon: 'success',
    })
    // Patch local state so the panel re-renders without a full GET.
    emit('updated', {
      status: res.status,
      data: {
        ...(props.draft.data ?? {}),
        _finalized_document: {
          path: res.path,
          uploaded_at: new Date().toISOString(),
          original_filename: res.original_filename,
          byte_length: res.byte_length,
        },
      },
    })
  } catch (err: any) {
    showToast({
      title: err?.statusMessage || err?.message || 'Upload failed.',
      icon: 'error',
    })
  } finally {
    isUploading.value = false
    uploadProgress.value = ''
  }
}

async function viewFinalized() {
  // Re-mint a fresh signed URL — the existing /url endpoint reads
  // the row's storage_path; we want the _finalized_document.path
  // instead, so call the upload endpoint's GET-shaped sibling… but
  // there isn't one yet. Cheap workaround: open in a new window via
  // a server endpoint that redirects to a fresh signed URL. For now,
  // fall back to a bespoke fetch + window.open(blob_url).
  if (!finalized.value) return
  try {
    const r = await $fetch<{ url: string }>(
      `/api/document-drafts/${props.draft.id}/finalized-url`,
    ).catch(() => null)
    if (r?.url) {
      window.open(r.url, '_blank', 'noopener,noreferrer')
      return
    }
    // No dedicated endpoint — gracefully degrade with a hint that
    // the path is on file but the signed URL needs the upload-time
    // response. Operators typically download once at upload-time.
    showToast({
      title: 'PDF on file. Re-upload to download a fresh copy, or open from S3 directly.',
      icon: 'info',
    })
  } catch (err: any) {
    showToast({ title: err?.message || 'Could not open PDF', icon: 'error' })
  }
}
</script>

<template>
  <section class="ui-card p-4">
    <header class="mb-3 flex items-baseline justify-between gap-3">
      <div>
        <h2 class="text-card-title">Notarized document</h2>
        <p class="mt-0.5 text-meta">
          Upload the final, tax-stamped + notarized PDF after offline signing.
          Status auto-advances to <span class="font-medium">signed</span> on first upload.
        </p>
      </div>
      <span
        :class="[
          'inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide',
          draft.status === 'signed'
            ? 'border-success/30 bg-success/10 text-success'
            : draft.status === 'archived'
              ? 'border-border bg-muted text-muted-foreground'
              : 'border-warning/30 bg-warning/10 text-warning',
        ]"
      >
        {{ draft.status }}
      </span>
    </header>

    <!-- Next-step prompt. Persistent while a notarized PDF is on file
         to remind the broker the contract phase is done and the
         post-signing transfer workflow needs to be started on the
         related deal. Kept generic — drafts don't carry a deal_id
         directly (links live through envelope_documents), and the
         broker knows which deal this draft belongs to. -->
    <div
      v-if="finalized"
      class="mb-3 flex items-start gap-2 rounded-md border border-primary/25 bg-primary/5 p-3 text-sm"
    >
      <span aria-hidden="true" class="text-base leading-none">→</span>
      <div class="flex-1 text-foreground">
        <p class="font-medium">Notarized contract on file.</p>
        <p class="mt-0.5 text-meta">
          Continue on the deal page where this draft is attached to start the
          transfer document workflow (CGT, DST, BIR CAR, transfer tax, title
          transfer, tax declaration).
        </p>
      </div>
      <NuxtLink
        to="/deals"
        class="shrink-0 rounded-md border border-primary/30 bg-card px-2.5 py-1 text-xs font-semibold text-primary transition-colors hover:bg-primary/10"
      >
        Go to deals
      </NuxtLink>
    </div>

    <!-- Already-uploaded state -->
    <div
      v-if="finalized"
      class="rounded-md border border-success/25 bg-success/5 p-3"
    >
      <div class="flex items-start gap-3">
        <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-success/15 text-success">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
            <polyline points="14 2 14 8 20 8" />
            <path d="M9 15l2 2 4-4" />
          </svg>
        </div>
        <div class="min-w-0 flex-1">
          <p class="truncate text-sm font-medium text-foreground">
            {{ finalized.original_filename || 'Notarized PDF' }}
          </p>
          <p class="text-[11px] text-muted-foreground">
            <span v-if="finalized.byte_length">{{ formatSize(finalized.byte_length) }} · </span>
            Uploaded {{ formatTs(finalized.uploaded_at) }}
          </p>
        </div>
        <div class="flex shrink-0 gap-2">
          <button
            type="button"
            class="btn-secondary"
            :disabled="isUploading"
            @click="viewFinalized"
          >
            View
          </button>
          <button
            type="button"
            class="btn-secondary"
            :disabled="isUploading"
            @click="pickFile"
          >
            Replace
          </button>
        </div>
      </div>
    </div>

    <!-- Empty state — file picker -->
    <div
      v-else
      class="rounded-md border border-dashed border-border bg-surface-2 p-4 text-center"
    >
      <p class="text-sm text-foreground">No final PDF on file yet.</p>
      <p class="mt-1 text-xs text-muted-foreground">
        Print the draft, complete tax stamps + notarization, then upload the scan here.
      </p>
      <button
        type="button"
        class="btn-primary mt-3 disabled:opacity-60"
        :disabled="isUploading"
        @click="pickFile"
      >
        <span v-if="isUploading">{{ uploadProgress || 'Uploading…' }}</span>
        <span v-else>Upload notarized PDF</span>
      </button>
    </div>

    <p
      v-if="isUploading && finalized"
      class="mt-2 text-[11px] text-muted-foreground"
    >
      {{ uploadProgress }}
    </p>

    <input
      ref="fileInputRef"
      type="file"
      accept="application/pdf"
      class="sr-only"
      @change="onFileChange"
    />
  </section>
</template>
