import * as yup from 'yup'

export const ListingRawSchema = yup.object().shape({
  listing_id: yup.number().required(),
  title: yup.string().required(),
  status: yup.string().required(),
  condition: yup.string().required(),
  description: yup.string().required(),
  unit_number: yup.string().required(),
  for_sale: yup.boolean().required(),
  for_rent: yup.boolean().required(),
  sale_price: yup.number().nullable(),
  rent_price: yup.number().nullable(),
  sale_price_per_sqm: yup.number().nullable(),
  rent_price_per_sqm: yup.number().nullable(),
  bedrooms: yup.number().required(),
  bathrooms: yup.number().required(),
  floor_area: yup.number().required(),
  lot_area: yup.number().nullable(),
  parking_spaces: yup.number().required(),
  lease_term: yup.number().required(),
  rent_advance: yup.number().required(),
  security_deposit: yup.number().required(),
  association_dues: yup.number().nullable(),
  availability_date: yup.string().required(),
  developer_name: yup.string().nullable(),
  property_name: yup.string().nullable(),
  property_type: yup.string().nullable(),
  property_category: yup.string().nullable(),
  street_address: yup.string().required(),
  category: yup.string().required(),
  year_built: yup.number().nullable(),
  coord: yup.mixed().nullable(),
  city_name: yup.string().nullable(),
  city_slug: yup.string().nullable(),
  is_online: yup.boolean().required(),
  barangay_name: yup.string().nullable(),
  contact_id: yup.number().nullable(),
  contact_name: yup.string().nullable(),
  contact_designation: yup.string().nullable(),
  contact_email: yup.string().nullable(),
  contact_home_phone: yup.string().nullable(),
  contact_mobile_number: yup.string().nullable(),
  contact_link: yup.string().nullable(),
  contact_notes: yup.string().nullable(),
  remarks: yup.string().nullable(),
  thumbnail: yup.string().required(),
  created_at: yup.string().required(),
  updated_at: yup.string().required(),
  created_by: yup.number().nullable(),
  created_by_name: yup.string().nullable(),
})

export const ListingColumnsSchema = yup.object().shape({
  listing_data: yup.object().shape({
    listing_id: yup.number().required(),
    title: yup.string().required(),
    thumbnail: yup.string().required(),
    is_online: yup.boolean().required(),
    column_name: yup.string().required().oneOf(['Listing']),
    unit_number: yup.string().nullable(),
    street_address: yup.string().nullable(),
    visible: yup.boolean().required(),
  }),
  price: yup.object().shape({
    sale_price: yup.number().nullable(),
    rent_price: yup.number().nullable(),
    column_name: yup.string().required().oneOf(['Price']),
    visible: yup.boolean().required(),
  }),
  price_per_sqm: yup.object().shape({
    sale_price_per_sqm: yup.number().nullable(),
    rent_price_per_sqm: yup.number().nullable(),
    column_name: yup.string().required().oneOf(['Price per sqm']),
    visible: yup.boolean().required(),
  }),
  condition: yup.object().shape({
    value: yup.string().required(),
    column_name: yup.string().required().oneOf(['Condition']),
    visible: yup.boolean().required(),
  }),
  city: yup.object().shape({
    value: yup.string().nullable(),
    city_slug: yup.string().nullable(),
    column_name: yup.string().required().oneOf(['City']),
    visible: yup.boolean().required(),
  }),
  availability: yup.object().shape({
    value: yup.string().required(),
    column_name: yup.string().required().oneOf(['Availability']),
    visible: yup.boolean().required(),
  }),
  designation: yup.object().shape({
    value: yup.string().nullable(),
    column_name: yup.string().required().oneOf(['Designation']),
    visible: yup.boolean().required(),
  }),
  category: yup.object().shape({
    value: yup.string().nullable(),
    column_name: yup.string().required().oneOf(['Category']),
    visible: yup.boolean().required(),
  }),
  contact: yup.object().shape({
    id: yup.number().nullable(),
    name: yup.string().nullable(),
    designation: yup.string().nullable(),
    email: yup.string().nullable(),
    home_phone: yup.string().nullable(),
    mobile_number: yup.string().nullable(),
    column_name: yup.string().required().oneOf(['Contact']),
    visible: yup.boolean().required(),
  }),
  bedrooms: yup.object().shape({
    value: yup.number().required(),
    column_name: yup.string().required().oneOf(['Bedrooms']),
    visible: yup.boolean().required(),
  }),
  bathrooms: yup.object().shape({
    value: yup.number().required(),
    column_name: yup.string().required().oneOf(['Bathrooms']),
    visible: yup.boolean().required(),
  }),
  floor_area: yup.object().shape({
    value: yup.number().required(),
    column_name: yup.string().required().oneOf(['Floor Area']),
    visible: yup.boolean().required(),
  }),
  lot_area: yup.object().shape({
    value: yup.number().nullable(),
    column_name: yup.string().required().oneOf(['Lot Area']),
    visible: yup.boolean().required(),
  }),
  barangay: yup.object().shape({
    value: yup.string().nullable(),
    column_name: yup.string().required().oneOf(['Barangay']),
    visible: yup.boolean().required(),
  }),
  parking_spaces: yup.object().shape({
    value: yup.number().required(),
    column_name: yup.string().required().oneOf(['Parking Spaces']),
    visible: yup.boolean().required(),
  }),
  property_type: yup.object().shape({
    value: yup.string().required(),
    column_name: yup.string().required().oneOf(['Property Type']),
    visible: yup.boolean().required(),
  }),
  status: yup.object().shape({
    label: yup.string().required(),
    value: yup.string().required(),
    column_name: yup.string().required().oneOf(['Status']),
    visible: yup.boolean().required(),
  }),
  remarks: yup.object().shape({
    value: yup.string().nullable(),
    column_name: yup.string().required().oneOf(['Remarks']),
    visible: yup.boolean().required(),
  }),
  created_at: yup.object().shape({
    value: yup.string().required(),
    column_name: yup.string().required().oneOf(['Created At']),
    visible: yup.boolean().required(),
  }),
  actions: yup.object().shape({
    column_name: yup.string().required().oneOf(['Actions']),
    visible: yup.boolean().required(),
  }),
  is_online: yup.object().shape({
    value: yup.boolean().required(),
    column_name: yup.string().required().oneOf(['isOnline']),
    visible: yup.boolean().required(),
  }),
  just_created: yup.boolean().required().default(false),
  updated_at: yup.object().shape({
    value: yup.string().required(),
    column_name: yup.string().required().oneOf(['Last Update']),
    visible: yup.boolean().required(),
  }),
  uploaded_by: yup.object().shape({
    value: yup.string().required(),
    column_name: yup.string().required().oneOf(['Upl. By']),
    visible: yup.boolean().required(),
  }),
})

export const ListingImagesSchema = yup.object().shape({
  listing_id: yup.number().required(),
  media_id: yup.string().required(),
  file_name: yup.string().required(),
  extension: yup.string().required(),
  created_at: yup.date().required(),
  updated_at: yup.date().required()
})
